### ISSUE TITLE
Links already created with hash strategy doesn't work with path strategy

### ISSUE THREAD

**Issue by ismadev** [simpleclub/url_strategy#13]
Is there any solution to migrate from hash to path?

There are a lot of links of my web created with hash on linkedin, facebook, sent via email, sent via whatsap...
www.myweb.com/#/privacy
www.myweb.com/#/card
www.myweb.com/#/plans

If anybody clicks on one of these links, it wouldn't work on path strategy.
Is there any solution for these "already created" links to work now on path strategy?

Thanks!,

**Comment by creativecreatorormaybenot** [comment]
Hi :) Thanks for using the package and creating the issue @ismadev ❤️ 

There is unfortunately no way to address this with Flutter's default path strategy feature (we faced the same issue). However, you should be able to read the URL on app start and set the `initialRoute` on your `MaterialApp` accordingly 🙂 

```dart
import 'dart:html';

window.location.href;
```

**Comment by ismadev** [comment]
Thanks! I will try it. ❤️

**Comment by creativecreatorormaybenot** [comment]
Awesome. I will close this as this is not strictly related to the package.

**Comment by ismadev** [comment]
![image](https://user-images.githubusercontent.com/2325441/109181850-adcdbb00-778c-11eb-84b5-e529ddb4ca83.png)

If somebody has the same problem.
Here is a workaround:
- If you are using "setPathUrlStrategy();" and the url resolved contains the hash and a path, the page will not load.
- Uri.base.fragment contains the path, so you have to replace it in your generated route.
- The RouteSettings of the generated route must contain the path.
