### ISSUE TITLE
With Firefox, Beamer, and hosted with Firebase, nav problem : URL stuck

### ISSUE THREAD

**Issue by dleurs** [simpleclub/url_strategy#16]
Hello !

With Firefix, <a href="https://pub.dev/packages/beamer">Beamer</a> and firebase hosted flutter web, I got navigation issues : 
- I am inside home screen, "/", of my website
- I click on Player button, I am now on "/player", player screen
- I click on auto-generated back button, I am well on home screen but URL is stuck at "/player"

![Apr-02-2021 18-04-32](https://user-images.githubusercontent.com/58068925/113432582-ed1ba700-93dd-11eb-9822-622723e2b23a.gif)

The website : https://hex-game-fc1ed.web.app

I only have this issue when website is hosted thanks to firebase AND using firefox, not in local debug.<br/>
No problem with Chrome :

![Apr-02-2021 18-05-22](https://user-images.githubusercontent.com/58068925/113432653-0de3fc80-93de-11eb-932f-e8535c429861.gif)

Without url_strategy, every thing works on firefox, but with the "#" :

**Comment by creativecreatorormaybenot** [comment]
Hi @dleurs, thanks for using the package and creating the issue 🙂 

The actual functionality is not implemented in `url_strategy` but in https://github.com/flutter/flutter. Therefore, if you want to report any bugs regarding the functionality, you will have to file an issue there: https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=

I hope this is understandable. As `url_strategy` only forwards to the framework feature, there is nothing we can do about this in the package, unfortunately,

**Comment by dleurs** [comment]
Yes but as it is working fine without url_strategy (but with the "#") on Firefox, it is related to this package no ?

**Comment by creativecreatorormaybenot** [comment]
@dleurs the `url_strategy` package is only for convenience. The path strategy itself is implemented in the Flutter framework itself :) Enabling it without this package is inconvenient - but that is all.

Only the people at https://github.com/flutter/flutter will be able to address the issue.

**Comment by dleurs** [comment]
Ok i got it thanks
