### ISSUE TITLE
Opening Subpage in Browser throws 404 error

### ISSUE THREAD

**Issue by michaeldwu** [simpleclub/url_strategy#20]
Hello!

I'm facing an issue where the app routing works fine when I use in app navigation (i.e. clicking pages and tabs), but doesn't work when I open the url in browser:
open https://theremapp.com - works
open https://theremapp.com/transparency - doesn't work

Refreshes also do not work, once I was navigated to this new page.

Interestingly enough, this is not an issue when I run the app on my local host, but is an issue when I deploy. Thank you.

**Comment by creativecreatorormaybenot** [comment]
Hi @michaeldwu - thanks for opening the issue :)

Unfortunately, we will not be able to solve the issue in this repo. I am also not sure why it happens.  
The path strategy **functionality** is implemented in the framework itself. This means you would need to open an issue at https://github.com/flutter/flutter/issues to report the bug (about "path URL strategy in Flutter web").

**Comment by Ucoon** [comment]
is there any other soluction?

**Comment by sathish-xe** [comment]
Hey @michaeldwu, did you find any solution?

**Comment by creativecreatorormaybenot** [comment]
@sathish-xe Hi, this is most likely because your SPA is not configured properly. I have elaborated on it in my StackOverflow answer here:

https://stackoverflow.com/a/65709246/6509751

(See the notes section)
