### ISSUE TITLE
setNewRoutePathis not called in Routing 2.0

### ISSUE THREAD

**Issue by praharshbhatt** [simpleclub/url_strategy#22]
After adding ```setPathUrlStrategy();```, ```setNewRoutePath()``` was not called when overriding ```AppRouterDelegate``` to implement Routing 2.0.
This takes away from the ability to have URLs navigate the screens.

**Comment by creativecreatorormaybenot** [comment]
Hi @praharshbhatt, thanks for using the package, but routing is not part of the package.

The whole `PathUrlStrategy` is actually handled in the Flutter framework - this package is only for toggling it on.

So unfortunately, we will not be able to help you here. Please file an issue at https://github.com/flutter/flutter.
