### ISSUE TITLE
onUnknownRoute not called with PathUrlStrategy

### ISSUE THREAD

**Issue by Tom3652** [simpleclub/url_strategy#23]
Hello ! 

If i use the method ```setPathUrlStrategy()```, the method ```onUnknownRoute()``` is not called anymore and it redirects me to the main page.
The error is for example : 

```
Could not navigate to initial route.
The requested route name was: "/gfdjfc"
There was no corresponding route in the app, and therefore the initial route specified will be ignored and "/" will be used instead.
```

If i have the ```UrlPathStrategy``` it's working fine. 
Thanks

**Comment by creativecreatorormaybenot** [comment]
Hi @Tom3652 - thanks for using the package and opening the issue!

Unfortunately, none of the logic for the URL strategy is implemented in this package. The package only handles **setting** (activating) the URL strategy. All of the logic happens in https://github.com/flutter/flutter, so if you want to report an issue about the [`PathUrlStrategy`](https://api.flutter.dev/flutter/flutter_web_plugins/PathUrlStrategy-class.html), you will have to do so there.

**Comment by Tom3652** [comment]
Hello !

Thanks for the reply, yes i will open an issue there then :)

**Comment by creativecreatorormaybenot** [comment]
@Tom3652 👍 you can link it here for reference. I would love to help you, but truth is no matter what I change in the package, there is no way to fix it here.

**Comment by Tom3652** [comment]
I have found the solution myself !
The problem was that i had a ```home``` property on my ```MaterialApp``` main ```Widget```. 
So all the wrong routes were redirected to this ```home``` instead of calling the ```onUnknownRoute```. 
Sorry for the issue then everything works fine with this strategy and the package, if it can help others :)
