### ISSUE TITLE
Without `#`, how can I open flutter route via full address?

### ISSUE THREAD

**Issue by topex-psy** [simpleclub/url_strategy#27]
Let say I have named route `/login`. Now I'm using this `url_strategy` plugin so the URL would be:
https://f7dc-36-84-85-125.ngrok.io/login.

Then if I refresh the page, or if I open on the new tab. I suspect it'll be translated to:
https://f7dc-36-84-85-125.ngrok.io/login/index.html

which is of course non-existent on the server.
So it'll be dead 404 error, am I right?

So how can I open `/login` route via full address which is https://f7dc-36-84-85-125.ngrok.io/login?

**Comment by creativecreatorormaybenot** [comment]
That is not how it works. You need to simply route all paths to `index.html`. I have some more details in my [StackOverflow answer](https://stackoverflow.com/a/65709246/6509751), but in general, you should just try to find out how to rewrite all paths to `index.html` with your hosting solution (e.g. Firebase hosting).

**Comment by topex-psy** [comment]
I see now, my bad. So rerouting all addresses to index.html is doable on the server side. Sadly I'm a frontend human. Thank you for the direction. I'm closing it now.

**Comment by topex-psy** [comment]
just in case anybody need it, I have solved this on apache server with .htaccess file

```
RewriteEngine On
RewriteBase /
RewriteCond $1 !^(index\.html|assets|robots\.txt|favicon\.png)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ index.html [L]
```
