### ISSUE TITLE
query parameter with URI using PathUrlStrategy

### ISSUE THREAD

**Issue by lucas-sampaio-fluency** [simpleclub/url_strategy#32]
When I try to use setUrlStrategy(PathUrlStrategy()) to remove the # of the Flutter application URL, the query paramaters have a problem:

if the URL is like this: `https://domain.com/route/123?param=https://anotherdomain.com`
then the route returned in onGenerateRoute is cut off, like this: `https://domain.com/route/123?param=https:`, and I can't access the full value of the `param` query parameter (even when trying to use settings.name.routingData or settings.argument).

This only happens when I'm using PathUrlStrategy.

**Comment by creativecreatorormaybenot** [comment]
Hi @lucas-sampaio-fluency - thanks for opening the issue.

The path URL strategy is part of the Flutter framework. For any questions, please refer to StackOverflow. For any issues, please open them in the https://github.com/flutter/flutter repository.
