### ISSUE TITLE
Expected a value of type 'JavaScriptObject', but got one of type 'Null'

### ISSUE THREAD

**Issue by AliKarimiENT** [simpleclub/url_strategy#34]
Hello 
I have faced this issue
![image](https://user-images.githubusercontent.com/57004354/189518305-5875978f-5ee4-4cdd-bd17-289b776d081e.png)

**Comment by AliKarimiENT** [comment]
Hi
Anyone could understand this error. I don't know why this problem is happening when I run on Chrome

**Comment by Sese-Schneider** [comment]
Hi @AliKarimiENT 
Your issue seems to be related to `ExpandableFab` and not this package.
Closing your issue as unrelated.
