### ISSUE TITLE
Refresh page will lost current url path and come back to initial path including "#" at the end

### ISSUE THREAD

**Issue by mahammadbakr** [simpleclub/url_strategy#37]
I'm using url strategy along with auto route, i pass some query parameters through the page but once i want directly open that page including the queries then the app will come back to initial route and the # will appear for a bit...

Flutter version: 3.7.5
url_strategy version: 0.2.0

**Comment by Sese-Schneider** [comment]
Hey @mahammadbakr 
Could you provide us with a minimal reproducable sample to investigate the issue please?
