### ISSUE TITLE
Dart 3.0 beta incompatibility

### ISSUE THREAD

**Issue by mikhael28** [simpleclub/url_strategy#38]
Hey there! Love the package - wanted to make you aware that with the new Dart 3.0 beta (and Flutter 3.8/9 beta) the package behavior has regressed and as is no longer working - the # has reappeared, when running Flutter web locally. I haven't deployed to web prod, so I cannot verify whether the behavior is active there.

**Comment by cogesum** [comment]
> Hey there! Love the package - wanted to make you aware that with the new Dart 3.0 beta (and Flutter 3.8/9 beta) the package behavior has regressed and as is no longer working - the # has reappeared, when running Flutter web locally. I haven't deployed to web prod, so I cannot verify whether the behavior is active there.

I checked it on web prod. The problem repeats.

**Comment by Sese-Schneider** [comment]
The package is compatible and functional with the Dart 3.0 production for us.
Please share an error log if there are any issues.

**Comment by mikhael28** [comment]
It's all good on my end too, looks like things were resolved somehow. Cheers!
