### ISSUE TITLE
URLs identified as "Page with redirect" in the Google Search Console

### ISSUE THREAD

**Issue by ben55j** [simpleclub/url_strategy#39]
Hello,

I have a website using this package to remove the # character in the URLs of my pages. 
I am trying to get my pages indexed by Google, but each time they got rejected with the following message: 
"Page with redirect". 

I am wondering if the use of the package might be the cause of this redirection detected. Do you have any insights on it ?

Here are the kind of URLs I am tying to get indexed: https://www.servicesadom.com/pro/imene.bentaharr

Thank you, 
Benjamin

**Comment by Sese-Schneider** [comment]
Hi Benjamin,

Unfortunately we don't have any insights on your problem.
Flutter is notoriously difficult to have indexed correctly ...

Sebastian
