### ISSUE TITLE
Error: Dart library 'dart:ui_web' is not available on this platform.

### ISSUE THREAD

**Issue by Patrick386** [simpleclub/url_strategy#40]
My app is being developed to support both web and mobile. When I develop for the web first and then run it on mobile, I encounter the following package error:

```
main() {
...
  if(kIsWeb) {
  usePathUrlStrategy();
  }
...
}
```

Error:
```
Launching lib/main.dart on iPhone 14 in debug mode...
Running pod install...                                             19.8s
Running Xcode build...                                                  
Xcode build done.                                           292.3s
Failed to build iOS app
Error (Xcode): ../../flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:5:8: Error: Dart library 'dart:ui_web' is not available on this platform.


Could not build the application for the simulator.
Error launching application on iPhone 14.

```

**Comment by Sese-Schneider** [comment]
Thank you for your report @Patrick386 

Can you please share your imports in  `main.dart` file with us?
It looks like you're calling `usePathUrlStrategy();` on mobile or you are not importing the package, but a _specific file_ of our package.

**Comment by Patrick386** [comment]
> Thank you for your report @Patrick386
> 
> Can you please share your imports in `main.dart` file with us? It looks like you're calling `usePathUrlStrategy();` on mobile or you are not importing the package, but a _specific file_ of our package.

I created a small sample code and tested it. When using usePathUrlStrategy(), it works correctly without the need for 'if(kIsWeb)'

This is my mistake. I haven't been using the correct approach for Flutter multi-platform development. When running on mobile, I should have used it like this, but I didn't. I'll need to do more testing to see if there's another issue. Since all the code is already built for the web, I have to examine many screens. Thank you.

**Ex:**
```
import 'check_out_screen.dart'
  if(dart.library.html) 'check_out_screen_web.dart'; 
  if(dart.library.io) 'check_out_screen_mobile.dart'; 
```
